version: '3.8'
services:
  soap:
    build: ./WcfServiceLibrary1
    ports:
      - "8001:80"

  rest:
    build: ./API WCF
    ports:
      - "8002:80"

  grpc:
    build: ./GRPC
    ports:
      - "8003:80"